name: nobo_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  rxdart: ^0.27.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
